stages:
  fetch:
    cmd: uv run python src/fetch_air_data.py
    deps:
      - src/fetch_air_data.py
    params:
      - fetch.url
    outs:
      - src/data/raw/air/air_data.xml
    always_changed: true

  preprocess:
    cmd: uv run python src/preprocess_air_data.py
    deps:
      - src/preprocess_air_data.py
      - src/data/raw/air/air_data.xml
    params:
      - preprocess.station
    outs:
      - src/data/preprocessed/air:
          persist: true
