name: Fetch data on schedule

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: write

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  fetch_air:
    name: Fetch and pre-process air data
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: latest
          enable-cache: true

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: uv sync --frozen

      - name: Run fetch script
        run: uv run python src/fetch_air_data.py

      - name: Run pre-process script
        run: uv run python src/preprocess_air_data.py

      - name: Update DVC tracking
        run: uv run dvc add src/data

      - name: Commit DVC metadata changes
        run: |
          git add src/data.dvc
          git add src/.gitignore

          if git diff --cached --quiet; then
            echo "No data changes to commit."
            exit 0
          fi

          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"

          git commit -m "Updated air data on $(date -u +'%Y-%m-%d %H:%M:%S UTC')"

      - name: Push changes
        run: git push